// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow

import (
	"context"
	"sync"

	"github.com/cappuccinotm/dastracker/app/store"
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
//
//     func TestSomethingThatUsesInterface(t *testing.T) {
//
//         // make and configure a mocked Interface
//         mockedInterface := &InterfaceMock{
//             ListSubscribedJobsFunc: func(ctx context.Context, triggerName string) ([]store.Job, error) {
// 	               panic("mock out the ListSubscribedJobs method")
//             },
//             ListTrackersFunc: func(in1 context.Context) ([]Tracker, error) {
// 	               panic("mock out the ListTrackers method")
//             },
//             ListTriggersFunc: func(in1 context.Context) ([]store.Trigger, error) {
// 	               panic("mock out the ListTriggers method")
//             },
//         }
//
//         // use mockedInterface in code that requires Interface
//         // and then make assertions.
//
//     }
type InterfaceMock struct {
	// ListSubscribedJobsFunc mocks the ListSubscribedJobs method.
	ListSubscribedJobsFunc func(ctx context.Context, triggerName string) ([]store.Job, error)

	// ListTrackersFunc mocks the ListTrackers method.
	ListTrackersFunc func(in1 context.Context) ([]Tracker, error)

	// ListTriggersFunc mocks the ListTriggers method.
	ListTriggersFunc func(in1 context.Context) ([]store.Trigger, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListSubscribedJobs holds details about calls to the ListSubscribedJobs method.
		ListSubscribedJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TriggerName is the triggerName argument value.
			TriggerName string
		}
		// ListTrackers holds details about calls to the ListTrackers method.
		ListTrackers []struct {
			// In1 is the in1 argument value.
			In1 context.Context
		}
		// ListTriggers holds details about calls to the ListTriggers method.
		ListTriggers []struct {
			// In1 is the in1 argument value.
			In1 context.Context
		}
	}
	lockListSubscribedJobs sync.RWMutex
	lockListTrackers       sync.RWMutex
	lockListTriggers       sync.RWMutex
}

// ListSubscribedJobs calls ListSubscribedJobsFunc.
func (mock *InterfaceMock) ListSubscribedJobs(ctx context.Context, triggerName string) ([]store.Job, error) {
	if mock.ListSubscribedJobsFunc == nil {
		panic("InterfaceMock.ListSubscribedJobsFunc: method is nil but Interface.ListSubscribedJobs was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		TriggerName string
	}{
		Ctx:         ctx,
		TriggerName: triggerName,
	}
	mock.lockListSubscribedJobs.Lock()
	mock.calls.ListSubscribedJobs = append(mock.calls.ListSubscribedJobs, callInfo)
	mock.lockListSubscribedJobs.Unlock()
	return mock.ListSubscribedJobsFunc(ctx, triggerName)
}

// ListSubscribedJobsCalls gets all the calls that were made to ListSubscribedJobs.
// Check the length with:
//     len(mockedInterface.ListSubscribedJobsCalls())
func (mock *InterfaceMock) ListSubscribedJobsCalls() []struct {
	Ctx         context.Context
	TriggerName string
} {
	var calls []struct {
		Ctx         context.Context
		TriggerName string
	}
	mock.lockListSubscribedJobs.RLock()
	calls = mock.calls.ListSubscribedJobs
	mock.lockListSubscribedJobs.RUnlock()
	return calls
}

// ListTrackers calls ListTrackersFunc.
func (mock *InterfaceMock) ListTrackers(in1 context.Context) ([]Tracker, error) {
	if mock.ListTrackersFunc == nil {
		panic("InterfaceMock.ListTrackersFunc: method is nil but Interface.ListTrackers was just called")
	}
	callInfo := struct {
		In1 context.Context
	}{
		In1: in1,
	}
	mock.lockListTrackers.Lock()
	mock.calls.ListTrackers = append(mock.calls.ListTrackers, callInfo)
	mock.lockListTrackers.Unlock()
	return mock.ListTrackersFunc(in1)
}

// ListTrackersCalls gets all the calls that were made to ListTrackers.
// Check the length with:
//     len(mockedInterface.ListTrackersCalls())
func (mock *InterfaceMock) ListTrackersCalls() []struct {
	In1 context.Context
} {
	var calls []struct {
		In1 context.Context
	}
	mock.lockListTrackers.RLock()
	calls = mock.calls.ListTrackers
	mock.lockListTrackers.RUnlock()
	return calls
}

// ListTriggers calls ListTriggersFunc.
func (mock *InterfaceMock) ListTriggers(in1 context.Context) ([]store.Trigger, error) {
	if mock.ListTriggersFunc == nil {
		panic("InterfaceMock.ListTriggersFunc: method is nil but Interface.ListTriggers was just called")
	}
	callInfo := struct {
		In1 context.Context
	}{
		In1: in1,
	}
	mock.lockListTriggers.Lock()
	mock.calls.ListTriggers = append(mock.calls.ListTriggers, callInfo)
	mock.lockListTriggers.Unlock()
	return mock.ListTriggersFunc(in1)
}

// ListTriggersCalls gets all the calls that were made to ListTriggers.
// Check the length with:
//     len(mockedInterface.ListTriggersCalls())
func (mock *InterfaceMock) ListTriggersCalls() []struct {
	In1 context.Context
} {
	var calls []struct {
		In1 context.Context
	}
	mock.lockListTriggers.RLock()
	calls = mock.calls.ListTriggers
	mock.lockListTriggers.RUnlock()
	return calls
}
