# provided functions: env "NAME" - returns the value of environment variable NAME
# values <map> - returns a list of values of the map
# seq <list[string]> - serializes the list in form of "string1,string2,string3,..."

trackers:
  - name: asana
    driver: asana
    with:
      workspace_id: kazanexpress.ru

  - name: github_erp
    driver: github
    with:
      owner: KazanExpress
      name: erp-photostudio
      access_token: {{ env "GITHUB_ACCESS_TOKEN" }}

  - name: telegram
    driver: telegram
    with:
      token: {{ env "TELEGRAM_BOT_TOKEN" }}

  - name: customrpc
    driver: rpc

jobs:
  - name: update task in github when task in asana is updated
    on:
      tracker: asana
      with:
        action: "changed"
        fields: ["due_at", "due_on", "dependencies" ]
        resource: "task"
    do:
      - action: github_erp/update_task
        with:
          body: {{ .Update.Body }}
          title: {{ .Update.Title }}
          labels: {{ seq (values .Update.Fields) }}

      - action: telegram/send
        with:
          message: "Task \"{{.Update.Title}}\" has been updated, link: {{.Update.URL}}"

      - action: rpc/print
        with:
          message: "Task \"{{.Update.Title}}\" has been updated and printed to the terminal."

  - name: update task in asana when task in github is updated
    on:
      tracker: github_erp
      with:
        events: [ "issue" ]
