# provided functions:
# env "NAME" - returns the value of environment variable NAME
# values <map> - returns a list of values of the map
# seq <list[string]> - serializes the list in form of "string1,string2,string3,..."

trackers:
  - name: gh_dastracker
    driver: github
    with:
      owner: cappuccinotm
      name: dastracker
      user: '{{ env "GITHUB_USER" }}'
      access_token: '{{ env "GITHUB_ACCESS_TOKEN" }}'

  - name: customrpc
    driver: rpc
    with:
      address: '{{ env "CUSTOM_RPC_ADDRESS" }}'

triggers:
  - name: gh_task_updated
    in: gh_dastracker
    with:
      events: "issues"

jobs:
  - name: print task update if task is received
    on: gh_task_updated
    do:
      - if: 'string_contains(Update.Title, "[PTT]")' # means "Print To Terminal"
        do:
          - action: customrpc/Print
            detached: true
            with:
              message: |
                Task "{{.Update.Title}}" has been updated and printed to the terminal. 
                Body: 
                {{.Update.Body}}
